//Handles any kind of failure by providing a message
class Failure {
  final String message;

  const Failure([this.message = 'An unexpected error occurred!']);
}
